// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv0BV-rS5Plt0adowY4dqiWl7ofXCv83E',
    appId: '1:324499308305:web:609f1f04cb9992e81ed6b0',
    messagingSenderId: '324499308305',
    projectId: 'qatarreciclagem-fatec',
    authDomain: 'qatarreciclagem-fatec.firebaseapp.com',
    storageBucket: 'qatarreciclagem-fatec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALcWdtautmjvySpHcpINfVEqlqAPUQgeY',
    appId: '1:324499308305:android:8cc764344c62d6701ed6b0',
    messagingSenderId: '324499308305',
    projectId: 'qatarreciclagem-fatec',
    storageBucket: 'qatarreciclagem-fatec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3CgEsBCT4Zd7kDo06FM4wqnX5w98Ywvw',
    appId: '1:324499308305:ios:7987d3ba9ab1a8e31ed6b0',
    messagingSenderId: '324499308305',
    projectId: 'qatarreciclagem-fatec',
    storageBucket: 'qatarreciclagem-fatec.appspot.com',
    iosClientId: '324499308305-obh92bskqhj8ucoicd82spdbde0qj1iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.qatarreciclagem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3CgEsBCT4Zd7kDo06FM4wqnX5w98Ywvw',
    appId: '1:324499308305:ios:7987d3ba9ab1a8e31ed6b0',
    messagingSenderId: '324499308305',
    projectId: 'qatarreciclagem-fatec',
    storageBucket: 'qatarreciclagem-fatec.appspot.com',
    iosClientId: '324499308305-obh92bskqhj8ucoicd82spdbde0qj1iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.qatarreciclagem',
  );
}
